services:
  cli:
    build: .
    command:
    - sleep
    - infinity
    working_dir: /src
    volumes:
    # set this in .env
    - ${ARC_AGI_DATA}:/data
    - ./src:/src
  gpu:
    image: torch-notebook:latest
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities:
            - gpu
    ports:
    - 8888:8888

